/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArgInput: typeof import('./src/components/inkform/ArgInput.vue')['default']
    Bool: typeof import('./src/components/inkform/Bool.vue')['default']
    Cloud: typeof import('./src/components/icons/cloud.vue')['default']
    ElAnchor: typeof import('element-plus/es')['ElAnchor']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Enum: typeof import('./src/components/inkform/Enum.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    HeaderNav: typeof import('./src/components/headerNav.vue')['default']
    Identicon: typeof import('./src/components/identicon.vue')['default']
    Input: typeof import('./src/components/inkform/Input.vue')['default']
    InputAccount: typeof import('./src/components/inkform/InputAccount.vue')['default']
    InputBalance: typeof import('./src/components/inkform/InputBalance.vue')['default']
    InputBytes: typeof import('./src/components/inkform/InputBytes.vue')['default']
    InputHash: typeof import('./src/components/inkform/InputHash.vue')['default']
    InputHex: typeof import('./src/components/inkform/InputHex.vue')['default']
    InputNumber: typeof import('./src/components/inkform/InputNumber.vue')['default']
    InsList: typeof import('./src/components/insList.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    LoadingBox: typeof import('./src/components/loading-box.vue')['default']
    Logo: typeof import('./src/components/icons/logo.vue')['default']
    Miner: typeof import('./src/components/icons/miner.vue')['default']
    NavList: typeof import('./src/components/navList.vue')['default']
    Network: typeof import('./src/components/network.vue')['default']
    Option: typeof import('./src/components/inkform/Option.vue')['default']
    Picon: typeof import('./src/components/icons/picon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svgIcon.vue')['default']
  }
}
